set_property PACKAGE_PIN K3 [get_ports {leds[0]}]
set_property PACKAGE_PIN M1 [get_ports {leds[1]}]
set_property PACKAGE_PIN L1 [get_ports {leds[2]}]
set_property PACKAGE_PIN K6 [get_ports {leds[3]}]
set_property PACKAGE_PIN J5 [get_ports {leds[4]}]
set_property PACKAGE_PIN H5 [get_ports {leds[5]}]
set_property PACKAGE_PIN H6 [get_ports {leds[6]}]
set_property PACKAGE_PIN K1 [get_ports {leds[7]}]

set_property PACKAGE_PIN P17 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]